version: "3.7"

services:
  database:
    image: postgres
    container_name: database_car-rental
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=car-rental
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: car-rental
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
